export const notes = [
  {
    slug: 'degen-trading-obicle',
    title: 'Degen Trading Thread',
    author: '@obicle',
    authorUrl: 'https://twitter.com/obicle',
    category: 'Degen & Memecoin',
    topic: 'Trading · Memecoin',
    desc: 'Rangkuman thread belajar trading degen / memecoin dari @obicle.',
    href: '/notes/degen-trading-obicle',
    avatar: '/notes/assets/degen-trading-obicle/avatar.jpg',
    accent: 'green',
  },
  {
    slug: 'arbitrage-uyar121',
    title: 'Arbitrage From Zero #1',
    author: '@Uyar121',
    authorUrl: 'https://twitter.com/Uyar121',
    category: 'Arbitrage',
    topic: 'Arbitrage · Cross-chain',
    desc: 'Menguasai LayerZero & Stargate - belajar cross-chain arbitrage dari modal $20 dari @Uyar121.',
    href: '/notes/arbitrage-uyar121',
    avatar: '/notes/assets/arbitrage-uyar121/avatar.jpg',
    accent: 'purple',
  },
  {
    slug: 'arbitrage-uyar121-screening',
    title: 'Arbitrage From Zero #2',
    author: '@Uyar121',
    authorUrl: 'https://twitter.com/Uyar121',
    category: 'Arbitrage',
    topic: 'Arbitrage · Screening',
    desc: 'Screening Mastery - workflow lengkap nyari arbitrage opportunity dari Coingecko sampai DEX aggregator, dari @Uyar121.',
    href: '/notes/arbitrage-uyar121-screening',
    avatar: '/notes/assets/arbitrage-uyar121/avatar.jpg',
    accent: 'purple',
  },
  {
    slug: 'arbitrage-uyar121-wormhole',
    title: 'Arbitrage From Zero #3',
    author: '@Uyar121',
    authorUrl: 'https://twitter.com/Uyar121',
    category: 'Arbitrage',
    topic: 'Arbitrage · Wormhole',
    desc: 'Bedah bridge tool Wormhole - Portal Bridge, Token Verifier, Wormholescan, sampai jebakan menu Governor, dari @Uyar121.',
    href: '/notes/arbitrage-uyar121-wormhole',
    avatar: '/notes/assets/arbitrage-uyar121/avatar.jpg',
    accent: 'purple',
  },
  {
    slug: 'arbitrage-uyar121-ccip',
    title: 'Arbitrage From Zero #4',
    author: '@Uyar121',
    authorUrl: 'https://twitter.com/Uyar121',
    category: 'Arbitrage',
    topic: 'Arbitrage · Chainlink CCIP',
    desc: 'Bedah Chainlink CCIP, plus dua kasus nyata (blunder SLX dan cuan harian FLUID), dari @Uyar121.',
    href: '/notes/arbitrage-uyar121-ccip',
    avatar: '/notes/assets/arbitrage-uyar121/avatar.jpg',
    accent: 'purple',
  },
  {
    slug: 'arbitrage-uyar121-find-bridge',
    title: 'Arbitrage From Zero #5',
    author: '@Uyar121',
    authorUrl: 'https://twitter.com/Uyar121',
    category: 'Arbitrage',
    topic: 'Arbitrage · Cek Jalur Bridge',
    desc: 'Find the Right Bridge - cara cepat ngecek token pakai jalur LayerZero, Wormhole, atau CCIP lewat scanner, dari @Uyar121.',
    href: '/notes/arbitrage-uyar121-find-bridge',
    avatar: '/notes/assets/arbitrage-uyar121/avatar.jpg',
    accent: 'purple',
  },
]
